"use strict";

const $ = (s, root=document) => root.querySelector(s);
const esc = value => String(value ?? "").replace(/[&<>'"]/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]));
const state = {route:"home", token:localStorage.portalSession||"", deviceId:localStorage.portalDeviceId||"", deviceToken:localStorage.portalDeviceToken||"", data:null, transfer:null};
const caps = ["send_receive","files","clipboard","media","window_control","command_palette"];

function toast(message){const node=$("#toast");node.textContent=message;node.classList.add("show");setTimeout(()=>node.classList.remove("show"),2200)}
async function api(path, options={}){
  const headers = new Headers(options.headers||{});
  if(state.token) headers.set("Authorization",`Bearer ${state.token}`);
  if(options.body && !(options.body instanceof Blob) && typeof options.body!=="string") {headers.set("Content-Type","application/json");options.body=JSON.stringify(options.body)}
  const res=await fetch(path,{...options,headers});
  let value=null;const type=res.headers.get("content-type")||"";
  if(type.includes("json")) value=await res.json();
  if(!res.ok){if(res.status===401 && !path.startsWith("/api/pair")){state.token="";localStorage.removeItem("portalSession")}throw new Error(value?.message||`Portal error ${res.status}`)}
  return value;
}
function deviceName(){const apple=/iPhone|iPad/.test(navigator.userAgent);const android=/Android/.test(navigator.userAgent);return apple?"iPhone":android?"Android phone":"Phone browser"}
function publicId(){let id=localStorage.portalPublicId;if(!id){id=crypto.randomUUID();localStorage.portalPublicId=id}return id}

async function bootstrap(){
  const fragment=new URLSearchParams(location.hash.slice(1));
  history.replaceState(null,"",location.pathname);
  if(fragment.has("pair")) return pair(fragment.get("pair"));
  if(state.token){try{await refresh();if(fragment.has("vision"))await visionSelect(fragment.get("vision"));return}catch(e){}}
  if(state.deviceId&&state.deviceToken){try{const v=await api("/api/session",{method:"POST",body:{device_id:state.deviceId,device_token:state.deviceToken}});saveSession(v);await refresh();if(fragment.has("vision"))await visionSelect(fragment.get("vision"));return}catch(e){}}
  renderUnpaired();
}
function saveSession(v){state.token=v.session_token;localStorage.portalSession=state.token;if(v.device_id){state.deviceId=v.device_id;localStorage.portalDeviceId=v.device_id}if(v.device_token){state.deviceToken=v.device_token;localStorage.portalDeviceToken=v.device_token}}
async function pair(secret){
  renderPair("Requesting access…");
  try{
    const req=await api("/api/pair/request",{method:"POST",body:{secret,device_name:deviceName(),public_id:publicId(),capabilities:caps}});
    renderPair("Approve this phone on your PC",req.expires);
    const timer=setInterval(async()=>{try{const v=await fetch(`/api/pair/${req.request_id}`,{headers:{"X-Portal-Claim":req.claim_token}}).then(r=>r.json());if(v.status==="approved"){clearInterval(timer);saveSession(v);await refresh();toast("Connected to Portal")}else if(v.status==="denied"){clearInterval(timer);renderPair("Connection denied")}}catch(e){}},900);
  }catch(e){renderPair(e.message)}
}
function renderPair(message,expires){$("#app").innerHTML=`<section class="hero center"><div class="brand">PORTAL</div><h1>Your PC, in your pocket.</h1><p><span class="dot"></span>${esc(message)}</p><div class="paircaps">${caps.map(c=>`<span>${esc(c.replaceAll("_"," "))}</span>`).join("")}</div>${expires?`<p id="expiry" style="margin-top:28px"></p>`:""}</section>`;if(expires){const tick=()=>{$("#expiry").textContent=`Request expires in ${Math.max(0,Math.ceil(expires-Date.now()/1000))}s`};tick();setInterval(tick,1000)}}
function renderUnpaired(){$("#app").innerHTML=`<section class="hero center"><div class="brand">PORTAL</div><h1>Scan from your PC</h1><p>Open Portal on your Omarchy desktop and scan its temporary code. No account. Local network only.</p></section>`}
async function refresh(){state.data=await api("/api/state");render()}

function chrome(content){
  const media=state.data?.media?.[0];
  const canAudio=state.data?.device?.capabilities?.includes("audio");
  const transfer=state.transfer?`<aside class="media" id="transfer-status"><div class="meta"><strong>${esc(state.transfer.name)}</strong><span id="transfer-percent">${state.transfer.progress||0}% · sending</span><div class="progress"><i id="transfer-bar" style="width:${state.transfer.progress||0}%"></i></div></div><button class="icon" id="cancel-transfer">×</button></aside>`:"";
  return `<header class="top"><div class="brand">PORTAL</div><div class="status"><span class="dot"></span>${esc(location.hostname)}</div></header>${content}${transfer||media?transfer||`<aside class="media"><div class="meta"><strong>${esc(media.title||"Now Playing")}</strong><span>${esc(media.artist||media.id)}</span></div>${canAudio?`<button class="icon" data-volume="-0.05">−</button>`:""}<button class="icon" data-media="previous">‹</button><button class="icon" data-media="play-pause">${media.status==="Playing"?"Ⅱ":"▶"}</button><button class="icon" data-media="next">›</button>${canAudio?`<button class="icon" data-volume="0.05">+</button>`:""}</aside>`:""}<nav class="nav">${[["control","Control"],["windows","Windows"],["files","Files"],["command","Command"]].map(([id,label])=>`<button data-route="${id}" class="${state.route===id?"active":""}">${label}</button>`).join("")}</nav>`;
}
function render(){
  if(!state.data)return;
  let body=state.route==="home"?home():state.route==="control"?control():state.route==="windows"?windows():state.route==="files"?files():command();
  $("#app").innerHTML=chrome(body);bind();
}
function home(){return `<section class="center"><h1>● ${esc(location.hostname.toUpperCase())}</h1><p>Connected</p></section><button class="drop" id="drop"><strong>DROP OR PASTE<br>ANYTHING</strong><small>Tap for files · paste text below</small></button><textarea class="paste" id="paste" placeholder="Paste text, a URL, or clipboard content"></textarea><label class="secureline"><input id="secure" type="checkbox"> Secure Transfer — no history, 5 minute expiry</label><div class="actions"><button class="primary" id="send-text">Continue on PC</button><button class="secondary" id="pc-clipboard">PC Clipboard</button><button class="secondary" id="vision">Portal Vision</button></div><div class="grid" style="margin-top:24px"><button class="route" data-route="control">Control<span>Trackpad + keyboard</span></button><button class="route" data-route="windows">Windows<span>Workspaces + actions</span></button><button class="route" data-route="files">Files<span>Portal Inbox</span></button><button class="route" data-route="command">Command<span>Safe actions</span></button></div>`}
function control(){const allowed=state.data.device.capabilities;const ok=allowed.includes("pointer")&&allowed.includes("keyboard");return `<h1>Control</h1><p>${ok?"Move naturally. Tap for left click; two-finger tap for right click.":"Enable Pointer and Keyboard for this device on the PC."}</p><div class="trackpad" id="trackpad">${ok?"TRACKPAD":"PERMISSION REQUIRED"}</div><div class="actions"><button class="secondary" data-click="left">Left Click</button><button class="secondary" data-click="right">Right Click</button></div><input class="keyboard" id="keyboard" placeholder="Type on PC" ${ok?"":"disabled"}><div class="actions"><button class="chip" data-key="Return">Return</button><button class="chip" data-key="Escape">Esc</button><button class="chip" data-key="BackSpace">⌫</button></div>`}
function windows(){const groups={};for(const w of state.data.windows.windows)(groups[w.workspace?.name||"Other"]??=[]).push(w);const content=Object.entries(groups).sort().map(([ws,rows])=>`<div class="workspace">Workspace ${esc(ws)}</div><div class="list">${rows.map(w=>`<article class="row"><div class="meta"><strong>${esc(w.title||w.class)}</strong><span>${esc(w.class)}</span></div><button class="chip" data-window="${esc(w.address)}">Select</button></article>`).join("")}</div>`).join("");return `<h1>Windows</h1><p>${state.data.windows.windows.length} visible window${state.data.windows.windows.length===1?"":"s"}</p>${content||`<div class="empty">No windows are visible.</div>`}`}
function files(){const rows=state.data.inbox.map(item=>`<article class="row"><div class="meta"><strong>${item.secure?"SECURE · ":""}${esc(item.name)}</strong><span>${esc(item.kind.toUpperCase())} · ${formatSize(item.size)} · ${item.direction==="to_pc"?"→ PC":"→ PHONE"}</span></div>${item.content_path||["file","image"].includes(item.kind)?`<a class="chip" href="/api/inbox/${item.id}/content" data-download="${item.id}">Open</a>`:`<button class="chip" data-inbox="${item.id}" data-action="copy">Copy</button>`}<button class="chip" data-inbox="${item.id}" data-action="discard">×</button></article>`).join("");return `<h1>Portal Inbox</h1><p>Items expire automatically. Transferred files never execute or extract.</p><button class="secondary" id="choose-file">Send file to PC</button><h2>Recent</h2><div class="list">${rows||`<div class="empty">Your Portal Inbox is empty.</div>`}</div>`}
function command(){return `<h1>Command</h1><p>Curated desktop actions only. No arbitrary shell.</p><input class="search" id="search" placeholder="Search actions"><div class="list" id="commands" style="margin-top:14px">${state.data.actions.map(a=>`<button class="row" data-command="${a.id}"><div class="meta"><strong>${esc(a.title)}</strong><span>${esc(a.capability.replaceAll("_"," "))}</span></div><span>›</span></button>`).join("")}</div>${state.data.audio.length?`<h2>Audio output</h2><div class="list">${state.data.audio.map(a=>`<button class="row" data-audio="${a.id}"><div class="meta"><strong>${esc(a.name)}</strong><span>${a.default?"Current output":"Switch output"}</span></div></button>`).join("")}</div>`:""}`}
function formatSize(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1048576)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1048576).toFixed(1)} MB`}

function bind(){
  document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>{state.route=b.dataset.route;render()});
  document.querySelectorAll("[data-media]").forEach(b=>b.onclick=()=>api("/api/media",{method:"POST",body:{player:state.data.media[0].id,action:b.dataset.media}}).then(refresh).catch(e=>toast(e.message)));
  document.querySelectorAll("[data-volume]").forEach(b=>b.onclick=()=>api("/api/audio",{method:"POST",body:{action:"volume",delta:Number(b.dataset.volume)}}).catch(e=>toast(e.message)));
  if($("#cancel-transfer"))$("#cancel-transfer").onclick=()=>state.transfer?.xhr?.abort();
  if($("#drop")){const drop=$("#drop");drop.onclick=()=>$("#file-picker").click();drop.ondragover=e=>{e.preventDefault();drop.classList.add("drag")};drop.ondragleave=()=>drop.classList.remove("drag");drop.ondrop=e=>{e.preventDefault();sendFiles(e.dataTransfer.files)}}
  if($("#choose-file"))$("#choose-file").onclick=()=>$("#file-picker").click();
  if($("#send-text"))$("#send-text").onclick=sendText;
  if($("#pc-clipboard"))$("#pc-clipboard").onclick=async()=>{try{const value=await api("/api/clipboard");$("#paste").value=value.text||"";if(value.sensitive_guess)$("#secure").checked=true;toast(value.text?"PC clipboard ready":"PC clipboard is empty")}catch(e){toast(e.message)}};
  if($("#vision"))$("#vision").onclick=startVision;
  document.querySelectorAll("[data-inbox]").forEach(b=>b.onclick=()=>api(`/api/inbox/${b.dataset.inbox}/action`,{method:"POST",body:{action:b.dataset.action}}).then(()=>{toast(b.dataset.action==="discard"?"Discarded":"Copied to PC");refresh()}).catch(e=>toast(e.message)));
  document.querySelectorAll("[data-download]").forEach(link=>link.onclick=async e=>{e.preventDefault();try{const res=await fetch(link.href,{headers:{Authorization:`Bearer ${state.token}`}});if(!res.ok)throw new Error("Download failed");const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=link.closest(".row")?.querySelector("strong")?.textContent||"portal-item";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(err){toast(err.message)}});
  document.querySelectorAll("[data-window]").forEach(b=>b.onclick=()=>showWindow(b.dataset.window));
  document.querySelectorAll("[data-click]").forEach(b=>b.onclick=()=>controlAction({action:b.dataset.click}));
  document.querySelectorAll("[data-key]").forEach(b=>b.onclick=()=>controlAction({action:"key",key:b.dataset.key}));
  if($("#keyboard"))$("#keyboard").onchange=e=>{if(e.target.value)controlAction({action:"type",text:e.target.value}).then(()=>e.target.value="")};
  bindTrackpad();
  document.querySelectorAll("[data-command]").forEach(b=>b.onclick=()=>runCommand(b.dataset.command));
  document.querySelectorAll("[data-audio]").forEach(b=>b.onclick=()=>api("/api/audio",{method:"POST",body:{id:b.dataset.audio}}).then(()=>{toast("Audio output switched");refresh()}).catch(e=>toast(e.message)));
  if($("#search"))$("#search").oninput=e=>document.querySelectorAll("[data-command]").forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(e.target.value.toLowerCase()));
}
$("#file-picker").onchange=e=>sendFiles(e.target.files);
async function sendText(){const field=$("#paste"),text=field.value.trim();if(!text)return toast("Paste something first");const kind=/^https?:\/\//i.test(text)?"url":"text";try{await api("/api/continue",{method:"POST",body:{kind,text,secure:$("#secure").checked}});field.value="";toast(kind==="url"?"Opened on PC":"Copied to PC clipboard");await refresh()}catch(e){toast(e.message)}}
function uploadFile(file){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();state.transfer={name:file.name,progress:0,xhr};render();xhr.open("PUT",`/api/files?name=${encodeURIComponent(file.name)}`);xhr.setRequestHeader("Authorization",`Bearer ${state.token}`);xhr.setRequestHeader("Content-Type",file.type||"application/octet-stream");xhr.upload.onprogress=e=>{if(!e.lengthComputable)return;state.transfer.progress=Math.round(e.loaded/e.total*100);const bar=$("#transfer-bar"),label=$("#transfer-percent");if(bar)bar.style.width=`${state.transfer.progress}%`;if(label)label.textContent=`${state.transfer.progress}% · sending`};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error("Transfer failed"));xhr.onerror=()=>reject(new Error("Transfer failed"));xhr.onabort=()=>reject(new Error("Transfer cancelled"));xhr.send(file)})}
async function sendFiles(files){for(const file of files){try{toast(`Sending ${file.name}…`);await uploadFile(file);toast(`${file.name} sent`)}catch(e){toast(e.message)}finally{state.transfer=null}}await refresh()}
async function controlAction(body){try{await api("/api/control",{method:"POST",body})}catch(e){toast(e.message)}}
function bindTrackpad(){const pad=$("#trackpad");if(!pad||pad.textContent.includes("PERMISSION"))return;let last=null,moved=false;pad.onpointerdown=e=>{pad.setPointerCapture(e.pointerId);last=[e.clientX,e.clientY];moved=false;pad.classList.add("active")};pad.onpointermove=e=>{if(!last)return;const dx=e.clientX-last[0],dy=e.clientY-last[1];if(Math.abs(dx)+Math.abs(dy)>2){moved=true;controlAction({action:"move",dx:Math.round(dx*1.45),dy:Math.round(dy*1.45)});last=[e.clientX,e.clientY]}};pad.onpointerup=()=>{if(!moved)controlAction({action:"left"});last=null;pad.classList.remove("active")};pad.onwheel=e=>{e.preventDefault();controlAction({action:"scroll",dy:e.deltaY})}}
async function showWindow(address){try{const w=await api(`/api/windows/${encodeURIComponent(address)}`);const multi=state.data.windows.monitors.length>1;$("#app").innerHTML=chrome(`<button class="chip" id="back">← Windows</button><h1 style="margin-top:22px">${esc(w.class.toUpperCase())}</h1><p>${esc(w.title)}</p>${w.xray?`<div class="row"><div class="meta"><strong>X-Ray</strong><span>${esc(JSON.stringify(w.xray).slice(0,120))}</span></div></div>`:""}<div class="actions"><button class="primary" data-wa="focus">Focus</button><button class="secondary" data-wa="take">Take This</button><button class="secondary" data-wa="control">Control</button><button class="secondary" data-wa="workspace">Move workspace…</button>${multi?`<button class="secondary" data-wa="monitor">Move monitor…</button>`:""}<button class="secondary" data-wa="fullscreen">Fullscreen</button><button class="danger" data-wa="close">Close…</button></div>`);$("#back").onclick=()=>{state.route="windows";render()};document.querySelectorAll("[data-wa]").forEach(b=>b.onclick=async()=>{const action=b.dataset.wa;if(action==="control"){state.route="control";return render()}if(action==="close"&&!confirm(`Close ${w.title}?`))return;let value="";if(action==="workspace")value=prompt("Workspace name or number",w.workspace?.name||"")||"";if(action==="monitor")value=prompt("Monitor name",state.data.windows.monitors.map(m=>m.name).join(", "))||"";if((action==="workspace"||action==="monitor")&&!value)return;try{await api(`/api/windows/${encodeURIComponent(address)}/action`,{method:"POST",body:{action,value,confirmed:action==="close"}});toast(action==="take"?"Context added to phone":"Done");await refresh()}catch(e){toast(e.message)}})}catch(e){toast(e.message)}}
async function runCommand(id){let value="";if(id==="workspace")value=prompt("Workspace name or number","")||"";if(id==="screenshot")value=confirm("Capture active window? Cancel captures full screen.")?"active":"full";try{await api("/api/actions/run",{method:"POST",body:{id,value}});toast("Command sent");await refresh()}catch(e){toast(e.message)}}
async function startVision(){try{await api("/api/vision",{method:"POST",body:{active:true}});if(!("BarcodeDetector" in window)){state.route="windows";toast("Camera QR scanning unavailable; select a window from the live list");return refresh()}$("#app").innerHTML=chrome(`<h1>Portal Vision</h1><p>Point at a temporary Portal marker on your PC.</p><video class="camera" id="camera" playsinline muted></video><button class="secondary" id="cancel-camera" style="width:100%;margin-top:12px">Cancel Vision</button>`);const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});const video=$("#camera");video.srcObject=stream;await video.play();const detector=new BarcodeDetector({formats:["qr_code"]});let stopped=false;$("#cancel-camera").onclick=()=>{stopped=true;stream.getTracks().forEach(t=>t.stop());api("/api/vision",{method:"POST",body:{active:false}});render()};const scan=async()=>{if(stopped)return;try{const codes=await detector.detect(video);for(const code of codes){const url=new URL(code.rawValue);const token=new URLSearchParams(url.hash.slice(1)).get("vision");if(token){stopped=true;stream.getTracks().forEach(t=>t.stop());return visionSelect(token)}}}catch(e){}requestAnimationFrame(scan)};scan()}catch(e){toast(e.message)}}
async function visionSelect(token){try{const w=await api("/api/vision/select",{method:"POST",body:{token}});await api("/api/vision",{method:"POST",body:{active:false}});await refresh();showWindow(w.address)}catch(e){toast(e.message);state.route="windows";render()}}
if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
bootstrap();
setInterval(()=>{if(state.token&&document.visibilityState==="visible"&&!document.querySelector(".camera")&&!/^(INPUT|TEXTAREA)$/.test(document.activeElement?.tagName||""))refresh().catch(()=>{})},5000);
